using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class ThemeSelector : MonoBehaviour
{
    [SerializeField] private Image[] themeButtons; // 4 bela kvadrata
    [SerializeField] private Color selectedColor = Color.yellow;
    [SerializeField] private Color normalColor = Color.white;

    private int selectedTheme = -1;

    public void SelectTheme(int index)
    {
        selectedTheme = index;
        for (int i = 0; i < themeButtons.Length; i++)
            themeButtons[i].color = i == index ? selectedColor : normalColor;
    }

    public void PlaySelectedTheme()
    {
        // Ako igrač nije ništa kliknuo, neka bude tema 0
        if (selectedTheme == -1) selectedTheme = 0;

        // Ako ThemeData ne postoji, napravi ga programski
        if (ThemeData.Instance == null)
        {
            GameObject go = new GameObject("ThemeDataAutoGenerated");
            go.AddComponent<ThemeData>();
          
        }

        // Sada sigurno postoji, pa upiši temu
        ThemeData.Instance.SelectedTheme = selectedTheme;

        // Učitaj scenu
        UnityEngine.SceneManagement.SceneManager.LoadScene("Theme1");
    
}
}